import { PrismaClient, MenuCategory } from '@prisma/client'

const prisma = new PrismaClient()

type DishSeed = {
  name: string
  description: string
  category: MenuCategory
  is_vegetarian: boolean
  is_vegan: boolean
  is_jain: boolean
  is_halal: boolean
  contains_nuts: boolean
  contains_gluten: boolean
  contains_dairy: boolean
  contains_eggs: boolean
  proteins: string[]
  spice_level: string
  cuisine_type: string
  ingredients: string[]
  history: string
  nutrition: { calories: number; protein_g: number; carbs_g: number; fat_g: number; fiber_g: number }
}

const dishes: DishSeed[] = [
  // ── SOUP & SALAD ─────────────────────────────────────────────────────────
  {
    name: 'Shorba',
    description: 'Aromatic spiced chicken or vegetable broth, slow-cooked with whole spices.',
    category: 'SOUP_SALAD',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Chicken'], spice_level: 'MEDIUM', cuisine_type: 'Mughlai',
    ingredients: ['Chicken', 'Onion', 'Tomato', 'Ginger', 'Garlic', 'Coriander', 'Cumin seeds', 'Bay leaf', 'Black pepper', 'Fresh coriander'],
    history: 'Shorba derives from the Arabic word "shurba" (soup) and entered Indian cuisine through the Mughal court. Emperors and their nobles consumed it as a warming starter. Over centuries it evolved into regional variants across the subcontinent, each adding local spices.',
    nutrition: { calories: 45, protein_g: 6, carbs_g: 3, fat_g: 1, fiber_g: 0 },
  },
  {
    name: 'Tomato Soup',
    description: 'Creamy tomato soup tempered with mustard seeds, curry leaves and a hint of spice.',
    category: 'SOUP_SALAD',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Tomatoes', 'Onion', 'Garlic', 'Ginger', 'Cream', 'Butter', 'Mustard seeds', 'Curry leaves', 'Sugar', 'Black pepper'],
    history: 'Tomato soup became popular in Indian banquet menus during the colonial era when western soups were adapted with local spices. Today it is a staple starter at weddings and formal dinners across India.',
    nutrition: { calories: 60, protein_g: 1, carbs_g: 8, fat_g: 3, fiber_g: 1 },
  },
  {
    name: 'Kachumber Salad',
    description: 'Crisp cucumber, tomato, and onion salad dressed with lemon and chat masala.',
    category: 'SOUP_SALAD',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Cucumber', 'Tomato', 'Onion', 'Green chilli', 'Fresh coriander', 'Lemon juice', 'Chaat masala', 'Salt'],
    history: 'Kachumber is a simple, everyday salad found across India. The name comes from the Hindi word for chopped. It serves as a palate cleanser and accompaniment to rich curries and biryanis at festive meals.',
    nutrition: { calories: 25, protein_g: 1, carbs_g: 5, fat_g: 0, fiber_g: 1 },
  },
  {
    name: 'Raita',
    description: 'Chilled yoghurt dip with grated cucumber, cumin, and fresh coriander.',
    category: 'SOUP_SALAD',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Yoghurt', 'Cucumber', 'Roasted cumin powder', 'Fresh coriander', 'Mint leaves', 'Salt', 'Red chilli powder'],
    history: 'Raita has been part of Indian cuisine for over a thousand years, documented in ancient Ayurvedic texts as a cooling condiment. Yoghurt is considered a digestive aid, and raita is traditionally served alongside spicy mains to balance heat and aid digestion.',
    nutrition: { calories: 55, protein_g: 3, carbs_g: 5, fat_g: 2, fiber_g: 0 },
  },

  // ── APPETIZERS ────────────────────────────────────────────────────────────
  {
    name: 'Samosa',
    description: 'Crisp pastry filled with spiced potato and peas, served with mint and tamarind chutneys.',
    category: 'APPETIZER',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['All-purpose flour', 'Potatoes', 'Green peas', 'Cumin seeds', 'Coriander', 'Garam masala', 'Ginger', 'Green chilli', 'Amchur (dry mango powder)', 'Oil'],
    history: 'The samosa traces its origins to Central Asia ("sambosa") and arrived in India with traders and Mughal influences in the 13th–14th centuries. Persian-language texts from the era describe it as a stuffed pastry. Today it is arguably the most popular snack in South Asia.',
    nutrition: { calories: 130, protein_g: 3, carbs_g: 18, fat_g: 6, fiber_g: 2 },
  },
  {
    name: 'Paneer Tikka',
    description: 'Marinated cottage cheese cubes grilled in a tandoor until charred and smoky.',
    category: 'APPETIZER',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Paneer'], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['Paneer', 'Yoghurt', 'Red chilli powder', 'Turmeric', 'Garam masala', 'Lemon juice', 'Ginger-garlic paste', 'Bell peppers', 'Onion', 'Chaat masala'],
    history: 'Paneer tikka is a vegetarian adaptation of the Mughal tandoori tradition. As chicken tikka became popular in the 20th century, Indian caterers developed an equivalent for the large vegetarian population. It is now a cornerstone of Indian wedding menus.',
    nutrition: { calories: 210, protein_g: 14, carbs_g: 6, fat_g: 15, fiber_g: 1 },
  },
  {
    name: 'Chicken Tikka',
    description: 'Tender chicken pieces marinated in yoghurt and spices, chargrilled in a tandoor.',
    category: 'APPETIZER',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Chicken'], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['Chicken breast', 'Yoghurt', 'Ginger-garlic paste', 'Red chilli powder', 'Turmeric', 'Garam masala', 'Lemon juice', 'Mustard oil', 'Kashmiri chilli', 'Chaat masala'],
    history: 'Chicken tikka has roots in the Mughal tradition of cooking skewered meats in clay ovens. The dish rose to global fame when it inspired Chicken Tikka Masala — said to be invented in Glasgow in the 1970s. The original boneless tikka remains a staple at North Indian restaurants worldwide.',
    nutrition: { calories: 165, protein_g: 25, carbs_g: 3, fat_g: 6, fiber_g: 0 },
  },
  {
    name: 'Seekh Kebab',
    description: 'Minced lamb mixed with herbs and spices, skewered and cooked over charcoal.',
    category: 'APPETIZER',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Lamb'], spice_level: 'MEDIUM', cuisine_type: 'Mughlai',
    ingredients: ['Minced lamb', 'Onion', 'Green chilli', 'Ginger', 'Garlic', 'Coriander leaves', 'Mint leaves', 'Garam masala', 'Cumin powder', 'Cardamom'],
    history: 'Seekh kebab (from Arabic "sikka" — skewer) was brought to India by Persian and Turkish traders. The Mughal emperors refined it at their court kitchens. Lucknow and Lahore are credited with producing the most delicate versions, where the meat is pounded so fine it melts on the tongue.',
    nutrition: { calories: 185, protein_g: 18, carbs_g: 4, fat_g: 11, fiber_g: 0 },
  },
  {
    name: 'Pakora',
    description: 'Assorted vegetables dipped in spiced chickpea batter and deep-fried until golden.',
    category: 'APPETIZER',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['Chickpea flour (besan)', 'Onion', 'Spinach', 'Green chilli', 'Ginger', 'Cumin seeds', 'Ajwain', 'Turmeric', 'Red chilli powder', 'Oil'],
    history: 'Pakoras have been a monsoon snack in India for centuries, mentioned in ancient Sanskrit texts as "pakvavata". The word itself derives from Sanskrit "pakva" (cooked). Typically enjoyed with tea during rains, they are now a fixture at weddings and festive spreads.',
    nutrition: { calories: 150, protein_g: 4, carbs_g: 16, fat_g: 8, fiber_g: 2 },
  },
  {
    name: 'Goat Boti Kebab',
    description: 'Tender goat pieces marinated overnight and grilled over open flame.',
    category: 'APPETIZER',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Goat'], spice_level: 'HOT', cuisine_type: 'Mughlai',
    ingredients: ['Goat (bone-in)', 'Yoghurt', 'Raw papaya paste', 'Ginger-garlic paste', 'Red chilli powder', 'Garam masala', 'Mustard oil', 'Lemon juice', 'Coal (for smoking)', 'Chaat masala'],
    history: 'Boti kebab is a speciality of Old Delhi and Lucknow, where whole goat pieces were marinated and slow-grilled over coal in the Mughal tradition. Raw papaya is used as a tenderiser, a technique perfected by court chefs to serve succulent meat at royal feasts.',
    nutrition: { calories: 220, protein_g: 22, carbs_g: 3, fat_g: 14, fiber_g: 0 },
  },
  {
    name: 'Prawn Koliwada',
    description: 'Crispy fried prawns marinated in a tangy coastal spice blend.',
    category: 'APPETIZER',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: false, contains_eggs: false,
    proteins: ['Prawn'], spice_level: 'HOT', cuisine_type: 'Maharashtrian',
    ingredients: ['Prawns', 'Rice flour', 'Chickpea flour', 'Kokum or lemon juice', 'Red chilli powder', 'Turmeric', 'Ginger-garlic paste', 'Cumin', 'Coriander', 'Oil'],
    history: 'Koliwada refers to the fishing village settlements (Koli communities) along the Mumbai coastline. This preparation was created by Koli fisherwomen who fried fresh catch in a sharp spice blend. It gained city-wide popularity in the 1960s and is now a staple Mumbai street snack.',
    nutrition: { calories: 175, protein_g: 16, carbs_g: 10, fat_g: 8, fiber_g: 1 },
  },
  {
    name: 'Aloo Tikki',
    description: 'Golden potato patties stuffed with spiced chickpeas, topped with chutneys.',
    category: 'APPETIZER',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['Potatoes', 'Chickpeas', 'Cumin seeds', 'Ginger', 'Green chilli', 'Coriander', 'Garam masala', 'Amchur', 'Rice flour', 'Oil'],
    history: 'Aloo tikki is believed to have originated in Uttar Pradesh and became a defining street food of North India. The British colonisers reportedly influenced its resemblance to the potato cake, but Indian cooks transformed it with local spices. Today it is central to chaat culture.',
    nutrition: { calories: 120, protein_g: 3, carbs_g: 20, fat_g: 4, fiber_g: 2 },
  },

  // ── MAIN COURSE ───────────────────────────────────────────────────────────
  {
    name: 'Butter Chicken',
    description: 'Slow-cooked chicken in a rich tomato and butter sauce with aromatic spices.',
    category: 'MAIN_COURSE',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Chicken'], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Chicken', 'Tomatoes', 'Butter', 'Cream', 'Cashews', 'Onion', 'Ginger-garlic paste', 'Garam masala', 'Kashmiri red chilli', 'Dried fenugreek (kasuri methi)'],
    history: 'Butter Chicken (Murgh Makhani) was reportedly invented by Kundan Lal Gujral at Moti Mahal restaurant in Old Delhi around 1950. Left-over tandoori chicken was simmered in a tomato-butter gravy to prevent it from drying out. The dish became a global ambassador of Indian cuisine.',
    nutrition: { calories: 290, protein_g: 24, carbs_g: 8, fat_g: 18, fiber_g: 1 },
  },
  {
    name: 'Paneer Makhani',
    description: 'Cottage cheese cubes in a velvety tomato-cream sauce with butter and spices.',
    category: 'MAIN_COURSE',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Paneer'], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Paneer', 'Tomatoes', 'Butter', 'Cream', 'Cashews', 'Onion', 'Ginger-garlic paste', 'Garam masala', 'Kashmiri red chilli', 'Kasuri methi'],
    history: 'Paneer Makhani is the vegetarian sibling of Butter Chicken, developed at the same Moti Mahal restaurant in Delhi. As paneer became the cornerstone of North Indian vegetarian cooking, the makhani sauce — rich with tomatoes, butter, and cream — was adapted for it. Today it anchors vegetarian banquet menus.',
    nutrition: { calories: 310, protein_g: 14, carbs_g: 9, fat_g: 24, fiber_g: 1 },
  },
  {
    name: 'Rogan Josh',
    description: 'Classic Kashmiri lamb curry cooked with whole spices and Kashmiri chillies.',
    category: 'MAIN_COURSE',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Lamb'], spice_level: 'HOT', cuisine_type: 'Kashmiri',
    ingredients: ['Lamb', 'Kashmiri red chilli', 'Fennel seeds', 'Ginger powder', 'Cardamom', 'Cloves', 'Cinnamon', 'Yoghurt', 'Mustard oil', 'Asafoetida (hing)'],
    history: 'Rogan Josh is a hallmark of Wazwan, the traditional Kashmiri multi-course feast. Its name comes from Persian — "rogan" (oil/fat) and "josh" (heat/passion). The Mughals brought Persian influences to Kashmir, where the dish evolved using local ingredients like Ratanjot (a natural dye giving it its distinctive red colour).',
    nutrition: { calories: 280, protein_g: 26, carbs_g: 5, fat_g: 17, fiber_g: 1 },
  },
  {
    name: 'Dal Makhani',
    description: 'Black lentils and kidney beans slow-cooked overnight with butter and cream.',
    category: 'MAIN_COURSE',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Lentils'], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Black lentils (urad dal)', 'Red kidney beans (rajma)', 'Butter', 'Cream', 'Tomatoes', 'Onion', 'Ginger-garlic paste', 'Garam masala', 'Cumin', 'Kasuri methi'],
    history: 'Dal Makhani was also created at Moti Mahal in Delhi by Kundan Lal Gujral, who slow-cooked black lentils overnight on dying embers. The long cooking time — up to 18 hours in traditional restaurants — gives it a silky texture. The "dal" was called "Maa ki Dal" (mother\'s lentil) in Punjab for generations before butter and cream elevated it.',
    nutrition: { calories: 195, protein_g: 10, carbs_g: 20, fat_g: 9, fiber_g: 5 },
  },
  {
    name: 'Palak Paneer',
    description: 'Fresh spinach purée with tender paneer cubes and aromatic spices.',
    category: 'MAIN_COURSE',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Paneer'], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['Spinach', 'Paneer', 'Onion', 'Tomato', 'Ginger', 'Garlic', 'Green chilli', 'Cumin seeds', 'Garam masala', 'Cream'],
    history: 'Palak paneer is a 20th-century creation popularised in Punjabi restaurants. Spinach (palak) was traditionally cooked as saag in rural Punjab, but the combination with paneer became a restaurant favourite in post-Partition Delhi when Punjabi refugees opened dhabas (roadside eateries) that would define North Indian cuisine.',
    nutrition: { calories: 235, protein_g: 12, carbs_g: 9, fat_g: 18, fiber_g: 3 },
  },
  {
    name: 'Chicken Korma',
    description: 'Tender chicken in a fragrant almond and cream sauce with whole spices.',
    category: 'MAIN_COURSE',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Chicken'], spice_level: 'MILD', cuisine_type: 'Mughlai',
    ingredients: ['Chicken', 'Yoghurt', 'Cream', 'Almonds', 'Cashews', 'Onion', 'Saffron', 'Cardamom', 'Cloves', 'Rose water'],
    history: 'Korma (from Urdu "qaorma", braising) is a royal Mughal preparation that dates to the 16th-century court of Akbar. The Ain-i-Akbari, Akbar\'s administrative document, records korma in royal menus. It was the centrepiece of celebratory feasts and remains the most aromatic curry in the Mughlai canon.',
    nutrition: { calories: 315, protein_g: 22, carbs_g: 7, fat_g: 22, fiber_g: 1 },
  },
  {
    name: 'Goat Curry',
    description: 'Traditional bone-in goat curry slow-cooked with onions and whole spices.',
    category: 'MAIN_COURSE',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Goat'], spice_level: 'HOT', cuisine_type: 'North Indian',
    ingredients: ['Goat (bone-in)', 'Onion', 'Tomato', 'Ginger-garlic paste', 'Coriander powder', 'Cumin powder', 'Red chilli powder', 'Turmeric', 'Garam masala', 'Mustard oil'],
    history: 'Goat (mutton) curry is one of the oldest meat preparations in South Asia, with roots predating Mughal rule. Goat was the preferred sacrificial animal in many communities, and festive goat curry has been central to Eid, weddings, and Hindu celebrations for centuries. Each region — Bengal, Kerala, Punjab — has a distinct version.',
    nutrition: { calories: 260, protein_g: 28, carbs_g: 6, fat_g: 14, fiber_g: 1 },
  },
  {
    name: 'Shahi Paneer',
    description: 'Paneer in a luxurious saffron-cream-cashew gravy with Mughlai notes.',
    category: 'MAIN_COURSE',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Paneer'], spice_level: 'MILD', cuisine_type: 'Mughlai',
    ingredients: ['Paneer', 'Cashews', 'Cream', 'Saffron', 'Onion', 'Milk', 'Cardamom', 'Cloves', 'Rose water', 'Ginger-garlic paste'],
    history: '"Shahi" means royal in Urdu. This dish was created to recreate the opulence of Mughal court cuisine for vegetarians. The use of saffron, rose water, and whole cashews are signatures of Mughlai cooking, adapted to paneer for Hindu courtiers who did not eat meat.',
    nutrition: { calories: 345, protein_g: 13, carbs_g: 10, fat_g: 29, fiber_g: 1 },
  },
  {
    name: 'Fish Curry',
    description: 'Coastal fish simmered in a tangy coconut and tamarind gravy with curry leaves.',
    category: 'MAIN_COURSE',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Fish'], spice_level: 'HOT', cuisine_type: 'South Indian',
    ingredients: ['White fish (Kingfish or Tilapia)', 'Coconut milk', 'Tamarind', 'Tomato', 'Onion', 'Curry leaves', 'Mustard seeds', 'Red chilli', 'Turmeric', 'Coconut oil'],
    history: 'Fish curry is the backbone of South Indian coastal cuisine, particularly in Kerala, Goa, and Tamil Nadu. Coconut and tamarind (kodampuli / kokum) have been used by coastal communities for centuries to preserve and flavour fish. Kerala\'s "fish molee" and Goa\'s "fish curry" are variations celebrated across the world.',
    nutrition: { calories: 195, protein_g: 22, carbs_g: 8, fat_g: 9, fiber_g: 1 },
  },
  {
    name: 'Kadai Chicken',
    description: 'Chicken stir-fried in a spiced tomato and bell pepper base in an iron wok.',
    category: 'MAIN_COURSE',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Chicken'], spice_level: 'HOT', cuisine_type: 'North Indian',
    ingredients: ['Chicken', 'Bell peppers', 'Tomatoes', 'Onion', 'Ginger-garlic paste', 'Coriander seeds', 'Red chilli', 'Garam masala', 'Cream', 'Kasuri methi'],
    history: 'Kadai chicken gets its name from the wok (kadai or karahi) it is cooked in. It emerged in Punjabi roadside dhabas in the mid-20th century, prized for its bold, dry-ish texture and smoky charred notes from the high-heat wok. The freshly ground spice blend ("kadai masala") is what distinguishes it from other chicken dishes.',
    nutrition: { calories: 250, protein_g: 26, carbs_g: 7, fat_g: 13, fiber_g: 2 },
  },
  {
    name: 'Nihari',
    description: 'Slow-braised beef or lamb shank stew with whole spices, best eaten at dawn.',
    category: 'MAIN_COURSE',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: false, contains_eggs: false,
    proteins: ['Beef', 'Lamb'], spice_level: 'HOT', cuisine_type: 'Mughlai',
    ingredients: ['Beef or lamb shank', 'Wheat flour (for thickening)', 'Ginger', 'Garlic', 'Onion', 'Ghee', 'Nihari masala', 'Bone marrow', 'Coriander leaves', 'Ginger julienne'],
    history: 'Nihari (from Arabic "nahar" — day/morning) was historically eaten before Fajr (dawn prayers) by Mughal labourers and later by the nobility in Old Delhi. It was traditionally cooked overnight in massive deghs (cauldrons). After the fall of the Mughal empire, Nihari cooks migrated to Lucknow and Hyderabad, spreading the dish. Karachi and Delhi still have century-old nihari shops.',
    nutrition: { calories: 310, protein_g: 30, carbs_g: 10, fat_g: 17, fiber_g: 1 },
  },
  {
    name: 'Aloo Gobi',
    description: 'Cauliflower and potatoes tossed with turmeric, cumin, and coriander.',
    category: 'MAIN_COURSE',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['Cauliflower', 'Potatoes', 'Onion', 'Tomato', 'Ginger', 'Garlic', 'Turmeric', 'Cumin seeds', 'Coriander powder', 'Green chilli'],
    history: 'Aloo Gobi is a humble everyday dish of North India, elevated globally by the 1999 British film Bend It Like Beckham. Though a home-cooked staple, it reflects the Punjabi tradition of dry-cooked (sukhi) sabzi using seasonal vegetables. Cauliflower arrived in India via Portuguese traders in the late 1600s.',
    nutrition: { calories: 110, protein_g: 3, carbs_g: 18, fat_g: 4, fiber_g: 3 },
  },
  {
    name: 'Lamb Vindaloo',
    description: 'Fiery Goan lamb curry marinated in vinegar and a bold spice paste.',
    category: 'MAIN_COURSE',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Lamb'], spice_level: 'VERY_HOT', cuisine_type: 'Goan',
    ingredients: ['Lamb', 'Malt vinegar', 'Kashmiri red chilli', 'Garlic', 'Ginger', 'Cumin', 'Cinnamon', 'Cloves', 'Black pepper', 'Potatoes'],
    history: 'Vindaloo originates from the Portuguese "carne de vinha d\'alhos" (meat in wine-vinegar and garlic). Portuguese colonisers brought this preservation method to Goa in the 15th century. Goan cooks replaced wine with palm vinegar and added a fierce spice paste, creating what became the most famous (and feared) curry in the world.',
    nutrition: { calories: 295, protein_g: 25, carbs_g: 12, fat_g: 16, fiber_g: 2 },
  },

  // ── RICE & BIRYANI ───────────────────────────────────────────────────────
  {
    name: 'Chicken Biryani',
    description: 'Fragrant basmati rice layered with spiced chicken, saffron, and caramelised onions.',
    category: 'RICE_BIRYANI',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Chicken'], spice_level: 'MEDIUM', cuisine_type: 'Hyderabadi',
    ingredients: ['Basmati rice', 'Chicken', 'Fried onions (birista)', 'Saffron', 'Yoghurt', 'Ghee', 'Whole spices (bay leaf, cloves, cardamom)', 'Mint leaves', 'Rose water', 'Kewra water'],
    history: 'Biryani\'s origins are debated — some trace it to Persia ("birinj" = rice), others to the Mughal armies cooking meat and rice together in cauldrons. Hyderabad\'s Nizam court developed the dum pukht (steam-sealed pot) technique in the 18th century, creating the definitive Hyderabadi biryani. Today there are over 50 regional varieties in India.',
    nutrition: { calories: 320, protein_g: 22, carbs_g: 38, fat_g: 9, fiber_g: 1 },
  },
  {
    name: 'Goat Biryani',
    description: 'Dum-cooked basmati rice with slow-braised goat and aromatic whole spices.',
    category: 'RICE_BIRYANI',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Goat'], spice_level: 'MEDIUM', cuisine_type: 'Hyderabadi',
    ingredients: ['Basmati rice', 'Goat (bone-in)', 'Fried onions (birista)', 'Saffron', 'Yoghurt', 'Ghee', 'Ginger-garlic paste', 'Whole spices', 'Mint leaves', 'Raw papaya (tenderiser)'],
    history: 'Goat biryani is the most prized version of biryani in South Asia, served at weddings and Eid feasts. The Hyderabadi royal court favoured goat over chicken for its richer flavour. Raw papaya paste is traditionally used to tenderise the meat, a technique passed down through generations of biryani cooks (ustads).',
    nutrition: { calories: 345, protein_g: 26, carbs_g: 38, fat_g: 11, fiber_g: 1 },
  },
  {
    name: 'Mutton Biryani',
    description: 'Slow-cooked lamb layered with saffron rice and sealed with dough for dum cooking.',
    category: 'RICE_BIRYANI',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Lamb'], spice_level: 'MEDIUM', cuisine_type: 'Hyderabadi',
    ingredients: ['Basmati rice', 'Lamb', 'Fried onions', 'Saffron', 'Yoghurt', 'Ghee', 'Whole spices', 'Mint', 'Kewra water', 'Rose water'],
    history: 'Mutton biryani is the Lucknawi (Awadhi) variation of the Hyderabadi original, distinguished by a lighter spice profile and pakki (pre-cooked meat) technique. The Nawabs of Awadh elevated biryani to an art form in the 18th-19th centuries, and Lucknow is still considered the spiritual home of the most delicate biryanis.',
    nutrition: { calories: 355, protein_g: 24, carbs_g: 38, fat_g: 12, fiber_g: 1 },
  },
  {
    name: 'Vegetable Biryani',
    description: 'Aromatic basmati rice cooked dum-style with seasonal vegetables and whole spices.',
    category: 'RICE_BIRYANI',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MEDIUM', cuisine_type: 'Indian',
    ingredients: ['Basmati rice', 'Mixed vegetables (carrot, beans, peas, cauliflower)', 'Fried onions', 'Yoghurt', 'Saffron', 'Ghee', 'Whole spices', 'Mint', 'Cashews', 'Raisins'],
    history: 'Vegetable biryani was developed as a vegetarian alternative to meat biryani for Hindu and Jain communities at Mughal courts and later in temple towns. It became prominent in South India, where cities like Bangalore popularised it with local vegetables and spice profiles distinct from the Hyderabadi tradition.',
    nutrition: { calories: 250, protein_g: 6, carbs_g: 42, fat_g: 7, fiber_g: 3 },
  },
  {
    name: 'Prawn Biryani',
    description: 'Coastal biryani with juicy prawns, coconut, and fragrant rice.',
    category: 'RICE_BIRYANI',
    is_vegetarian: false, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: ['Prawn'], spice_level: 'MEDIUM', cuisine_type: 'South Indian',
    ingredients: ['Basmati rice', 'Prawns', 'Coconut milk', 'Fried onions', 'Tomato', 'Ginger-garlic paste', 'Ghee', 'Whole spices', 'Mint', 'Curry leaves'],
    history: 'Prawn biryani is a coastal speciality of Kerala, Goa, and Andhra Pradesh. Kerala\'s Malabar coast has long been a hub of the spice trade, and Arab traders who settled there brought biryani techniques that melded with local coconut-based cooking. The result is a lighter, aromatics-forward biryani unique to the region.',
    nutrition: { calories: 290, protein_g: 20, carbs_g: 38, fat_g: 7, fiber_g: 1 },
  },
  {
    name: 'Jeera Rice',
    description: 'Steamed basmati rice tempered with cumin seeds, ghee, and fresh coriander.',
    category: 'RICE_BIRYANI',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Basmati rice', 'Cumin seeds', 'Ghee', 'Fresh coriander', 'Salt', 'Cloves', 'Bay leaf'],
    history: 'Jeera rice is a simple staple of North Indian home cooking, serving as a lighter alternative to biryani at meals. Cumin (jeera) has been used in Indian cooking for over 3,000 years and is valued for its digestive properties. The dish accompanies almost every dal and curry in the Indian kitchen.',
    nutrition: { calories: 185, protein_g: 3, carbs_g: 36, fat_g: 3, fiber_g: 0 },
  },
  {
    name: 'Pulao',
    description: 'Lightly spiced rice cooked with vegetables, peas, and aromatic spices.',
    category: 'RICE_BIRYANI',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Basmati rice', 'Green peas', 'Onion', 'Ghee', 'Bay leaf', 'Cardamom', 'Cloves', 'Cinnamon', 'Ginger', 'Salt'],
    history: 'Pulao (or pilaf) is one of the world\'s great rice dishes, with origins in ancient Persia. The word "pulao" appears in Sanskrit texts as "pulaka". It arrived in India through Persian and Central Asian trade routes and became the precursor to biryani. Lighter and simpler than biryani, pulao remains a beloved everyday rice dish.',
    nutrition: { calories: 195, protein_g: 4, carbs_g: 37, fat_g: 4, fiber_g: 2 },
  },

  // ── BREAD ────────────────────────────────────────────────────────────────
  {
    name: 'Garlic Naan',
    description: 'Leavened bread baked in a tandoor, brushed with garlic butter and fresh coriander.',
    category: 'BREAD',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['All-purpose flour', 'Yoghurt', 'Yeast', 'Sugar', 'Salt', 'Garlic', 'Butter', 'Fresh coriander', 'Milk', 'Oil'],
    history: 'Naan (from Persian "nan" = bread) has been baked in clay ovens across Central Asia and South Asia for over a thousand years. Earliest references appear in Amir Khusrau\'s 1300 CE writings about Delhi\'s Nizamuddin shrine. The Mughals popularised it in their court kitchens, where bakers (nanbai) crafted multiple varieties for the emperor.',
    nutrition: { calories: 290, protein_g: 9, carbs_g: 48, fat_g: 7, fiber_g: 2 },
  },
  {
    name: 'Tandoori Roti',
    description: 'Whole wheat flatbread baked directly on the walls of a clay tandoor.',
    category: 'BREAD',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Whole wheat flour (atta)', 'Water', 'Salt', 'Butter (to finish)'],
    history: 'The tandoor (clay oven) originated in the Indus Valley Civilization over 5,000 years ago. Tandoori roti is the most austere of Indian breads — unleavened whole wheat, baked at extreme heat. It remains the daily bread of Punjabi households and is the default bread at Indian wedding langar (community feasts).',
    nutrition: { calories: 180, protein_g: 6, carbs_g: 34, fat_g: 3, fiber_g: 4 },
  },
  {
    name: 'Puri',
    description: 'Deep-fried puffed whole wheat bread, a classic accompaniment to any Indian meal.',
    category: 'BREAD',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Whole wheat flour', 'Semolina', 'Salt', 'Oil (for dough)', 'Oil (for frying)'],
    history: 'Puri is mentioned in ancient Sanskrit texts and has been part of Hindu religious offerings for millennia. The puffing of the dough when it hits hot oil was considered auspicious — a sign that the divine had accepted the offering. Today it is central to prasad (temple food), religious feasts, and the beloved "puri-aloo" breakfast of North India.',
    nutrition: { calories: 215, protein_g: 5, carbs_g: 28, fat_g: 10, fiber_g: 2 },
  },
  {
    name: 'Laccha Paratha',
    description: 'Multi-layered flaky whole wheat flatbread cooked on a griddle with butter.',
    category: 'BREAD',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Whole wheat flour', 'All-purpose flour', 'Ghee', 'Water', 'Salt', 'Butter (to finish)'],
    history: '"Laccha" means ring or layer in Hindi. The laccha paratha\'s multiple flaky layers are achieved through a technique of rolling, folding, and re-rolling the dough repeatedly — similar to puff pastry. It was developed in the royal kitchens of North India and remains the most prized paratha variety at weddings and banquets.',
    nutrition: { calories: 245, protein_g: 7, carbs_g: 37, fat_g: 9, fiber_g: 3 },
  },
  {
    name: 'Bhatura',
    description: 'Soft, deep-fried leavened bread traditionally paired with spiced chickpeas.',
    category: 'BREAD',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Punjabi',
    ingredients: ['All-purpose flour', 'Yoghurt', 'Semolina', 'Baking soda', 'Sugar', 'Salt', 'Oil', 'Oil (for frying)'],
    history: 'Bhatura was created in Punjab in the early 20th century and became inseparable from Chole (chickpeas) as "Chole Bhature" — one of the most beloved street-food combinations in North India. Post-Partition, Punjabi refugees brought it to Delhi, where it became a defining dish of the capital\'s food culture.',
    nutrition: { calories: 310, protein_g: 7, carbs_g: 44, fat_g: 12, fiber_g: 1 },
  },

  // ── DAL ──────────────────────────────────────────────────────────────────
  {
    name: 'Dal Tadka',
    description: 'Yellow lentils tempered with cumin, mustard seeds, garlic, and dried red chillies.',
    category: 'DAL',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Lentils'], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['Yellow lentils (toor dal)', 'Onion', 'Tomato', 'Garlic', 'Ginger', 'Cumin seeds', 'Mustard seeds', 'Dried red chilli', 'Turmeric', 'Ghee'],
    history: 'Dal tadka is the quintessential dhaba (roadside restaurant) dish of North India. The technique of "tadka" or "chaunk" — tempering whole spices in hot ghee and pouring it over cooked lentils — is an ancient Indian culinary practice described in Ayurvedic texts as a way to enhance both flavour and digestibility.',
    nutrition: { calories: 150, protein_g: 9, carbs_g: 22, fat_g: 4, fiber_g: 4 },
  },
  {
    name: 'Chole',
    description: 'Chickpeas simmered in a bold tomato and onion masala with tangy dried mango.',
    category: 'DAL',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Lentils'], spice_level: 'MEDIUM', cuisine_type: 'Punjabi',
    ingredients: ['Chickpeas', 'Onion', 'Tomato', 'Ginger-garlic paste', 'Amchur (dry mango)', 'Pomegranate powder', 'Cumin', 'Coriander', 'Tea bag (for colour)', 'Garam masala'],
    history: 'Chole (Punjabi chickpea curry) is a cornerstone of Sikh langar (community kitchen) food, where it has been served free to visitors of Gurdwaras for centuries. The black/dark colour comes from a unique Punjabi technique of boiling the chickpeas with a teabag. Chickpeas were one of the first crops domesticated in the Fertile Crescent, reaching India over 3,000 years ago.',
    nutrition: { calories: 165, protein_g: 9, carbs_g: 28, fat_g: 3, fiber_g: 7 },
  },
  {
    name: 'Rajma',
    description: 'Red kidney beans slow-cooked in a thick, spiced tomato-onion gravy.',
    category: 'DAL',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Lentils'], spice_level: 'MEDIUM', cuisine_type: 'North Indian',
    ingredients: ['Red kidney beans', 'Onion', 'Tomato', 'Ginger-garlic paste', 'Cumin seeds', 'Coriander powder', 'Garam masala', 'Chilli powder', 'Turmeric', 'Oil'],
    history: 'Kidney beans originated in the Americas and were introduced to India through Portuguese trade routes in the 16th century. "Rajma chawal" (rajma with rice) became the ultimate comfort food of Delhi and Punjab in the 20th century. It is a Sunday staple in millions of North Indian households and has an almost cult-like following.',
    nutrition: { calories: 155, protein_g: 9, carbs_g: 25, fat_g: 3, fiber_g: 7 },
  },
  {
    name: 'Sambhar',
    description: 'South Indian lentil stew with tamarind, tomatoes, and seasonal vegetables.',
    category: 'DAL',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: ['Lentils'], spice_level: 'MEDIUM', cuisine_type: 'South Indian',
    ingredients: ['Split pigeon peas (toor dal)', 'Tamarind', 'Tomatoes', 'Sambar powder', 'Curry leaves', 'Mustard seeds', 'Asafoetida', 'Drumstick (moringa)', 'Shallots', 'Dry red chilli'],
    history: 'Sambhar is arguably the most important dish of South Indian cuisine, originating in Tamil Nadu. One legend credits its creation to the Maratha ruler Sambhaji, who accidentally made a dal with tamarind instead of kokum. The dish became synonymous with South Indian identity and is the backbone of the traditional thali (plate meal).',
    nutrition: { calories: 95, protein_g: 5, carbs_g: 15, fat_g: 2, fiber_g: 4 },
  },

  // ── DESSERTS ─────────────────────────────────────────────────────────────
  {
    name: 'Gulab Jamun',
    description: 'Soft milk-solid dumplings soaked in rose-flavoured sugar syrup.',
    category: 'DESSERT',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Khoya (milk solids)', 'All-purpose flour', 'Baking soda', 'Milk', 'Sugar', 'Rose water', 'Cardamom', 'Saffron', 'Oil (for frying)', 'Pistachios (garnish)'],
    history: 'Gulab Jamun traces its ancestry to a Persian dessert called "luqmat al qadi" (judge\'s morsels) that Mughal rulers brought to India. The "gulab" (rose) comes from rose water in the syrup; "jamun" refers to the Indian blackberry fruit the dumplings resemble. The dish is now synonymous with celebrations — no Indian wedding ends without it.',
    nutrition: { calories: 175, protein_g: 3, carbs_g: 30, fat_g: 5, fiber_g: 0 },
  },
  {
    name: 'Gajar Halwa',
    description: 'Slow-cooked carrot pudding with milk, sugar, ghee, and topped with nuts.',
    category: 'DESSERT',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Carrots', 'Milk', 'Sugar', 'Ghee', 'Cardamom powder', 'Cashews', 'Almonds', 'Raisins', 'Khoya', 'Saffron'],
    history: 'Gajar (carrot) halwa is traditionally a winter dessert of North India, made when red Delhi carrots (gajar) are in season from November to February. The dish has been documented in Mughal-era cookbooks and is a fixture at weddings and festivals including Diwali and Lohri.',
    nutrition: { calories: 200, protein_g: 4, carbs_g: 28, fat_g: 9, fiber_g: 2 },
  },
  {
    name: 'Kheer',
    description: 'Creamy rice pudding slow-cooked in milk with saffron, cardamom, and nuts.',
    category: 'DESSERT',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Basmati rice', 'Full-fat milk', 'Sugar', 'Cardamom', 'Saffron', 'Almonds', 'Cashews', 'Pistachios', 'Rose water', 'Raisins'],
    history: 'Kheer (from Sanskrit "ksheer" = milk) is one of the oldest Indian desserts, mentioned in Ayurvedic texts and offered to Hindu deities for over 2,000 years. It is prepared during Navratri, Diwali, and Eid, beloved by all communities. The Mughal version — flavoured with saffron and rose water — became the most refined variant.',
    nutrition: { calories: 180, protein_g: 5, carbs_g: 28, fat_g: 6, fiber_g: 0 },
  },
  {
    name: 'Rasmalai',
    description: 'Soft paneer discs soaked in chilled saffron-cardamom milk, garnished with pistachios.',
    category: 'DESSERT',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Bengali',
    ingredients: ['Chenna (fresh paneer)', 'Full-fat milk', 'Sugar', 'Saffron', 'Cardamom', 'Pistachios', 'Rose water', 'Kewra water', 'Sugar syrup'],
    history: 'Rasmalai was invented by K.C. Das, a legendary Bengali sweet-maker, in Kolkata in the early 20th century. It is an elevated version of Ras Gulla (soft paneer in syrup) soaked in rich, reduced "rabri" (thickened milk). Bengali mishti (sweets) culture considers it the pinnacle of the art form.',
    nutrition: { calories: 195, protein_g: 7, carbs_g: 26, fat_g: 8, fiber_g: 0 },
  },
  {
    name: 'Kulfi',
    description: 'Dense Indian ice cream made with condensed milk in flavours like pistachio or mango.',
    category: 'DESSERT',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Full-fat milk', 'Condensed milk', 'Sugar', 'Cardamom', 'Pistachios', 'Saffron', 'Rose water', 'Cornflour'],
    history: 'Kulfi has been documented in India since the 16th century, when the Mughal emperor Akbar\'s kitchens were said to use caravans of mountain ice and salt to freeze flavoured milk mixtures. Unlike Western ice cream, kulfi is never churned — giving it a denser, richer texture. It was traditionally served in earthen cones (matka kulfi).',
    nutrition: { calories: 220, protein_g: 5, carbs_g: 28, fat_g: 11, fiber_g: 0 },
  },
  {
    name: 'Jalebi',
    description: 'Crispy spirals of batter fried and soaked in saffron sugar syrup.',
    category: 'DESSERT',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['All-purpose flour', 'Yoghurt', 'Saffron', 'Sugar', 'Cardamom', 'Rose water', 'Oil (for frying)', 'Yellow food colour'],
    history: 'Jalebi traces its origin to "Zalabiya" — a Middle Eastern sweet brought to India by Arabic-speaking traders and Sufi missionaries in the medieval period. The word appears in a 15th-century Sanskrit text "Priyamkarnrpakatha". It became embedded in Indian street food culture and is now the most-consumed sweet at temple fairs and wedding dessert stations.',
    nutrition: { calories: 155, protein_g: 1, carbs_g: 32, fat_g: 3, fiber_g: 0 },
  },
  {
    name: 'Ladoo',
    description: 'Round sweet balls made from besan or boondi, ghee, and sugar.',
    category: 'DESSERT',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: true, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Chickpea flour (besan)', 'Ghee', 'Sugar', 'Cardamom powder', 'Cashews', 'Almonds', 'Raisins', 'Pistachios'],
    history: 'Ladoo (or laddoo) is one of the oldest Indian sweets, with references in Ayurvedic texts from 300 BCE, where sesame ladoos were prescribed as a healing food. The besan ladoo variety became associated with the deity Ganesh and is offered at Ganesh Chaturthi. Today, different regions have distinct versions — motichoor, boondi, til, and rava ladoo.',
    nutrition: { calories: 190, protein_g: 4, carbs_g: 24, fat_g: 9, fiber_g: 2 },
  },

  // ── BEVERAGES ────────────────────────────────────────────────────────────
  {
    name: 'Mango Lassi',
    description: 'Chilled yoghurt drink blended with Alphonso mango pulp and a pinch of cardamom.',
    category: 'BEVERAGE',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Yoghurt', 'Alphonso mango pulp', 'Sugar', 'Cardamom powder', 'Saffron', 'Milk', 'Ice'],
    history: 'Lassi originated in the Punjab region over 3,000 years ago as a simple yoghurt-water mixture (chaas). The mango lassi — a sweetened variant with mango pulp — became popularised in Indian restaurants internationally in the 1970s and 80s. It is now perhaps the most globally recognised Indian drink.',
    nutrition: { calories: 150, protein_g: 4, carbs_g: 28, fat_g: 3, fiber_g: 1 },
  },
  {
    name: 'Sweet Lassi',
    description: 'Traditional chilled yoghurt drink sweetened with sugar and flavoured with rose water.',
    category: 'BEVERAGE',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Punjabi',
    ingredients: ['Yoghurt', 'Sugar', 'Rose water', 'Milk', 'Ice', 'Cardamom (optional)'],
    history: 'Sweet lassi is the ceremonial drink of Punjabi culture, served at weddings and after religious ceremonies. The thick, frothy Amritsari lassi — served in clay pots at the Golden Temple — is considered the gold standard. Lassi-wallahs (lassi vendors) have operated in Punjab\'s market squares for centuries.',
    nutrition: { calories: 120, protein_g: 4, carbs_g: 21, fat_g: 2, fiber_g: 0 },
  },
  {
    name: 'Masala Chai',
    description: 'Spiced tea brewed with milk, ginger, cardamom, and cinnamon.',
    category: 'BEVERAGE',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Black tea leaves', 'Milk', 'Water', 'Ginger', 'Cardamom', 'Cinnamon', 'Cloves', 'Black pepper', 'Sugar'],
    history: 'Chai (Sanskrit "chaya") has been brewed in India for over 5,000 years, though the British East India Company introduced Assam tea leaves in the 19th century to break China\'s monopoly. The "masala" (spiced) version was developed by Indian vendors as tea consumption spread from colonial elites to the masses in the early 20th century.',
    nutrition: { calories: 65, protein_g: 2, carbs_g: 10, fat_g: 2, fiber_g: 0 },
  },
  {
    name: 'Thandai',
    description: 'Chilled milk drink blended with almonds, fennel, rose petals, and saffron.',
    category: 'BEVERAGE',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Full-fat milk', 'Almonds', 'Cashews', 'Pistachios', 'Fennel seeds', 'Rose petals', 'Saffron', 'Cardamom', 'Pepper', 'Sugar'],
    history: 'Thandai (from Hindi "thanda" = cold) is the traditional drink of Holi and Maha Shivaratri. Sacred to Lord Shiva, it is offered at temples and consumed during festivals. The blend of nuts, seeds, and spices is considered cooling and energising — an Ayurvedic formulation to balance body heat during the spring festival season.',
    nutrition: { calories: 185, protein_g: 5, carbs_g: 22, fat_g: 9, fiber_g: 1 },
  },

  // ── LIVE COUNTERS ────────────────────────────────────────────────────────
  {
    name: 'Chaat Counter',
    description: 'Live chaat station with pani puri, papdi chaat, bhel puri, and dahi vada.',
    category: 'LIVE_COUNTER',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MEDIUM', cuisine_type: 'Indian',
    ingredients: ['Papdi (fried crisps)', 'Puri shells', 'Boiled potatoes', 'Chickpeas', 'Yoghurt', 'Tamarind chutney', 'Mint chutney', 'Sev (chickpea noodles)', 'Pomegranate', 'Chaat masala'],
    history: 'Chaat (from Sanskrit "chaatna" = to lick) has been street food in India since at least the Mughal era. The diversity of chaat — sweet, sour, spicy, crunchy — in a single bite encapsulates the philosophy of Indian cooking. Different cities claim distinct versions: Mumbai\'s bhel puri, Delhi\'s papdi chaat, and Kolkata\'s puchka are all regional expressions.',
    nutrition: { calories: 135, protein_g: 3, carbs_g: 22, fat_g: 5, fiber_g: 2 },
  },
  {
    name: 'Tawa Roti Counter',
    description: 'Fresh rotis and parathas made to order on a live tawa with assorted fillings.',
    category: 'LIVE_COUNTER',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'North Indian',
    ingredients: ['Whole wheat flour', 'Ghee', 'Butter', 'Potato filling', 'Paneer filling', 'Radish filling', 'Onion', 'Green chilli', 'Coriander'],
    history: 'The live tawa counter at Indian weddings is a crowd favourite, rooted in the tradition of village women cooking fresh rotis for the entire community at harvest festivals. The concept of watching flatbreads puff and char live became a luxury catering feature in the 1990s, symbolising warmth and freshness.',
    nutrition: { calories: 200, protein_g: 5, carbs_g: 32, fat_g: 7, fiber_g: 3 },
  },
  {
    name: 'Dosa Counter',
    description: 'Live South Indian dosa station with masala, onion, and plain varieties.',
    category: 'LIVE_COUNTER',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: false, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'South Indian',
    ingredients: ['Fermented rice and lentil batter', 'Potatoes', 'Onion', 'Mustard seeds', 'Curry leaves', 'Turmeric', 'Coconut chutney', 'Sambhar', 'Oil'],
    history: 'Dosa is documented in Tamil literature from the 8th century CE. The fermented batter (rice + urad dal) technique is unique — the fermentation adds beneficial probiotics and creates the crispy, thin texture. The masala dosa variety — with spiced potato filling — became the face of South Indian cuisine globally after Udupi restaurants spread across India in the 20th century.',
    nutrition: { calories: 170, protein_g: 4, carbs_g: 30, fat_g: 5, fiber_g: 2 },
  },
  {
    name: 'Pani Puri Counter',
    description: 'Interactive pani puri station with spiced mint and tamarind waters.',
    category: 'LIVE_COUNTER',
    is_vegetarian: true, is_vegan: true, is_jain: false, is_halal: true,
    contains_nuts: false, contains_gluten: true, contains_dairy: false, contains_eggs: false,
    proteins: [], spice_level: 'HOT', cuisine_type: 'Indian',
    ingredients: ['Semolina puri shells', 'Boiled potatoes', 'Chickpeas', 'Tamarind water', 'Mint-coriander water', 'Black salt', 'Cumin powder', 'Chilli powder', 'Onion', 'Coriander'],
    history: 'Pani puri (or golgappa/puchka) is perhaps India\'s most beloved street food. Its origin is disputed between different regions — Uttar Pradesh, Madhya Pradesh, and Bihar all claim it. The hollow, crisp shell is filled and consumed in a single bite — an experience so elemental that it has become a rite of passage for every Indian.',
    nutrition: { calories: 90, protein_g: 2, carbs_g: 16, fat_g: 3, fiber_g: 1 },
  },
  {
    name: 'Kulfi Counter',
    description: 'Live kulfi station serving pistachio, mango, and rose kulfi on demand.',
    category: 'LIVE_COUNTER',
    is_vegetarian: true, is_vegan: false, is_jain: false, is_halal: true,
    contains_nuts: true, contains_gluten: false, contains_dairy: true, contains_eggs: false,
    proteins: [], spice_level: 'MILD', cuisine_type: 'Indian',
    ingredients: ['Condensed milk', 'Cream', 'Pistachio', 'Mango pulp', 'Rose syrup', 'Cardamom', 'Saffron', 'Kulfi moulds', 'Falooda (optional)'],
    history: 'Kulfi counters became a fixture at Indian weddings in the 1980s, when refrigeration technology made on-site kulfi preparation feasible. The experience of watching kulfi unmoulded and sliced fresh — sometimes served with falooda (rose-milk noodles) — became synonymous with the end of a lavish Indian feast.',
    nutrition: { calories: 230, protein_g: 5, carbs_g: 29, fat_g: 11, fiber_g: 0 },
  },
]

async function main() {
  console.log(`Seeding ${dishes.length} global dishes with full details…`)
  let created = 0, updated = 0

  for (const dish of dishes) {
    const result = await prisma.globalDish.upsert({
      where: { name: dish.name },
      create: { ...dish, active: true },
      update: {
        description: dish.description,
        category: dish.category,
        is_vegetarian: dish.is_vegetarian,
        is_vegan: dish.is_vegan,
        is_jain: dish.is_jain,
        is_halal: dish.is_halal,
        contains_nuts: dish.contains_nuts,
        contains_gluten: dish.contains_gluten,
        contains_dairy: dish.contains_dairy,
        contains_eggs: dish.contains_eggs,
        proteins: dish.proteins,
        spice_level: dish.spice_level,
        cuisine_type: dish.cuisine_type,
        ingredients: dish.ingredients,
        history: dish.history,
        nutrition: dish.nutrition,
        active: true,
      },
    })
    if (result.created_at.getTime() === result.updated_at.getTime()) created++
    else updated++
  }

  console.log(`Done. ${created} created, ${updated} updated.`)
}

main()
  .catch(e => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
